### ISSUE TITLE
where to find wire_intents.json

### ISSUE THREAD

**Issue by akioolin** [openXC7/xc7k325t-blinky-nextpnr#34]
Dear Sirs:

after using https://github.com/kintex-chatter/toolchain-installer to install related toolchains, and the clone this project and execute "make BOARD=qmtech setup"

the error shows wire_intents.json is not found. where to find this file or how to generate ?

Many thanks.

BR, Akio

**Comment by hansfbaier** [comment]
Don't use this project with the toolchain installer, use https://github.com/kintex-chatter/demo-projects
